### ISSUE TITLE
only one bot joins 

### ISSUE THREAD

**Issue by DmnksLTU** [AdamHing/RobloxAFKBots#1]
only one bot joins the roblox game

**Comment by AdamHing** [comment]
I am currently working on a version 2 of this program with way more features and is much more efficient. 
Its not quite ready but you can take a look if you want. https://github.com/AdamHing/ROBO 

To solve your current issue I would make a custom set of bot accounts if you have not already. 

If all the bots managed to sign in and only one joined, than I think the problem is most likely the part after it clicks "join" and a there is a popup where it needs to click "Open Roblox". The way I made it is quite janky and unreliable. 

To fix this try replacing the image I provided called OpenRoblox.PNG with a screenshot of what it looks like on your machine.


hope this helps, I will be fixing this in version 2 as well. 

If the problem persists Send me the console output.
